apiVersion: v1
kind: Secret
metadata:
  name: {{ include "PaddleDoc.fullname" . }}-env
  labels:
    {{- include "PaddleDoc.labels" . | nindent 4 }}
type: Opaque
stringData:
  REDIS_URL: redis://{{ include "PaddleDoc.redisHost" . }}:{{ .Values.redis.port }}/0
