apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paddledoc.fullname" . }}-env
  labels:
    {{- include "paddledoc.labels" . | nindent 4 }}
type: Opaque
stringData:
  REDIS_URL: redis://{{ include "paddledoc.redisHost" . }}:{{ .Values.redis.port }}/0
